### ISSUE TITLE
Unintended Growth

### ISSUE THREAD

**Issue by Vinnie1961** [SynchronisedNerdism/KK_BE#2]
changing posistions (like cowgirl -> reverse cowgirl) during sex give a sudden boost to breast size, usually screwing it up and making it look ridiculous. also maybe having the nipple be not affected by the growth by adding numbers to the breast scale instead of size might be a better idea, perhapes as an alternative option to use

**Comment by SynchronisedNerdism** [comment]
Thanks for the bug report, I fixed the massive swelling issue
Although, Nipple size is already untouched by the plugin,  Humongous breasts are pretty glitched in Koikatsu. I put in some measures that might alleviate this issue just in case.
