### ISSUE TITLE
[Feature/Mod proposal] KK_BR

### ISSUE THREAD

**Issue by Lebleus** [SynchronisedNerdism/KK_BE#3]
Hello, 

Amazing mod, you've made.

In order to satisfy everyone kink, could you do the same with breast reduction ?

If both KK_BE and KK_BR could work together too, it would be amazing ! (With a trigger or something to choose which one to apply or something).

Last thing, I didn't check if this mod work with KKS.

Regards,

**Comment by SynchronisedNerdism** [comment]
> Hello,
> 
> Amazing mod, you've made.
> 
> In order to satisfy everyone kink, could you do the same with breast reduction ?
> 
> If both KK_BE and KK_BR could work together too, it would be amazing ! (With a trigger or something to choose which one to apply or something).
> 
> Last thing, I didn't check if this mod work with KKS.
> 
> Regards,

It actually already works 
just set the start size at something high like 1.0
then set the end size smaller than the start size at 0.0 or something
